create table users
(
    id bigint generated by default as identity
        constraint users_pkey
            primary key,
    name varchar(255) not null,
    password varchar(255) not null
);
create table bodytype
(
    id bigint generated by default as identity
        constraint bodytype_pkey
            primary key,
    description varchar(255) not null
);
create table brand
(
    id bigint generated by default as identity
        constraint brand_pkey
            primary key,
    description varchar(255) not null
);
create table category
(
    id bigint generated by default as identity
        constraint category_pkey
            primary key,
    description varchar(255)
);
create table enginetype
(
    id bigint generated by default as identity
        constraint enginetype_pkey
            primary key,
    description varchar(255) not null
);
create table transmission
(
    id bigint generated by default as identity
        constraint transmission_pkey
            primary key,
    description varchar(255) not null
);
create table wheeldrivetype
(
    id bigint generated by default as identity
        constraint wheeldrivetype_pkey
            primary key,
    description varchar(255) not null
);
create table image
(
    id bigint generated by default as identity
        constraint image_pkey
            primary key,
    filename varchar(255) not null,
    path varchar(255) not null
);
create table car
(
    id bigint generated by default as identity
        constraint car_pkey
            primary key,
    creationdate date,
    mileage integer,
    model varchar(255),
    price integer,
    bodytype_id bigint not null
        constraint fkl6ih0te63fabpjejo6arut675
            references bodytype,
    brand_id bigint not null
        constraint fkn1kx1h1f9kccf3m6xsm6belbv
            references brand,
    enginetype_id bigint not null
        constraint fkmm2f70vpbmxqdwfxl5frayjus
            references enginetype,
    transmission_id bigint not null
        constraint fk1qaofcrja57vbanxrh9axendk
            references transmission,
    wheeldrivetype_id bigint not null
        constraint fk5wqe1ev5x2o77ohib4ip37r9y
            references wheeldrivetype
);
create table item
(
    id bigint generated by default as identity
        constraint item_pkey
            primary key,
    description varchar(255) not null,
    sold boolean not null,
    car_id bigint not null
        constraint fk29cie2ksao2yg2exq4djkcm9v
            references car,
    user_id bigint not null
        constraint fk3jo8h7x0guh765jul6rrtngjl
            references users
);
create table item_category
(
    item_id bigint not null
        constraint fkaapxi3huul1b3smnwiplcpyyf
            references item,
    category_id bigint not null
        constraint fka0696xbdijl6c18j11u16egxl
            references category,
    constraint item_category_pkey
        primary key (item_id, category_id)
);
create table item_image
(
    item_id bigint not null
        constraint fk2mnbxd060hofqsa5cnp0ygjne
            references item,
    images_id bigint not null
        constraint uk_bb1xnd9aky4mn9ukvj8phmgsr
            unique
        constraint fks5la1bshf2x13taxc79194it8
            references image,
    constraint item_image_pkey
        primary key (item_id, images_id)
);
insert into bodytype (description) values ('Хэтчбэк'),
                                          ('Универсал'),
                                          ('Купе'),
                                          ('Кабриолет'),
                                          ('Внедорожник');
insert into brand (description) values ('Audi'),
                                       ('Volkswagen'),
                                       ('BMW'),
                                       ('Mercedes-Benz'),
                                       ('Skoda'),
                                       ('Lada'),
                                       ('Citroen'),
                                       ('Mazda'),
                                       ('Mitsubishi');
insert into enginetype (description) values ('Бензин'),
                                            ('Дизель'),
                                            ('Гибрид'),
                                            ('Электрический');
insert into transmission (description) values ('Автоматическая'),
                                              ('Механическая'),
                                              ('Роботизированная'),
                                              ('Вариатор');
insert into wheeldrivetype (description) values ('Полный'),
                                                ('Передний'),
                                                ('Задний');
insert into category (description) values ('Полноприводные'),
                                          ('Коробка Автомат'),
                                          ('Коробка Механика'),
                                          ('Кузов универсал'),
                                          ('Без пробега'),
                                          ('Не проданы еще'),
                                          ('Двигатель дизель');
